import {
  Lightbulb,
  ShieldCheck,
  ClipboardList,
  Network,
  Flame,
  Clock,
  Calendar,
  Award,
  Users,
  Building2,
  MapPin,
  Phone,
  Mail,
  CheckCircle2,
  Zap,
  Wrench,
  HardHat,
  Ruler,
  FileCheck2,
  GraduationCap,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  lightbulb: Lightbulb,
  "shield-check": ShieldCheck,
  clipboard: ClipboardList,
  network: Network,
  flame: Flame,
  clock: Clock,
  calendar: Calendar,
  award: Award,
  users: Users,
  building: Building2,
  "map-pin": MapPin,
  phone: Phone,
  mail: Mail,
  check: CheckCircle2,
  zap: Zap,
  wrench: Wrench,
  "hard-hat": HardHat,
  ruler: Ruler,
  certificate: FileCheck2,
  "graduation-cap": GraduationCap,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export const ICON_OPTIONS: { label: string; value: IconName }[] = [
  { label: "Lightbulb (lighting)", value: "lightbulb" },
  { label: "Shield Check (certified/safety)", value: "shield-check" },
  { label: "Clipboard (survey/design)", value: "clipboard" },
  { label: "Network (data/IT)", value: "network" },
  { label: "Flame (fire alarm)", value: "flame" },
  { label: "Clock (experience/years)", value: "clock" },
  { label: "Calendar (founded/date)", value: "calendar" },
  { label: "Award (recognition)", value: "award" },
  { label: "Users (team/people)", value: "users" },
  { label: "Building (offices/commercial)", value: "building" },
  { label: "Map Pin (location)", value: "map-pin" },
  { label: "Phone (contact)", value: "phone" },
  { label: "Mail (email)", value: "mail" },
  { label: "Check Circle (general tick)", value: "check" },
  { label: "Zap (electrical/power)", value: "zap" },
  { label: "Wrench (installation)", value: "wrench" },
  { label: "Hard Hat (site work)", value: "hard-hat" },
  { label: "Ruler (design/measurement)", value: "ruler" },
  { label: "Certificate (documentation)", value: "certificate" },
  { label: "Graduation Cap (training)", value: "graduation-cap" },
];
